baseURL = "https://a-creative.website/"
languageCode = "en-US"
title = "a creative solution | Owen Edwards"
theme = "archie"
copyright = "Owen Edwards © "

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    style = "github-dark"

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.typographer]
        disable = true

[pagination]
  pagerSize = 6

[params]
  mode = "dark"
  useCDN = false
  subtitle = "Creative ideas need creative solutions. Here's all my solutions :)"
  [params.author]
    email = '467487@pm.me'
    name = 'Owen Edwards'

[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/ooofruitsnacks"

[[menu.main]]
  name = "Home Page"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Blog Posts"
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "My Projects"
  url = "/my_projects/
  weight = 3

[[menu.main]]
  name = "About Me"
  url = "/about/"
  weight = 4

